[tool.poetry]
name = "africhain"
version = "0.1.0"
description = ""
authors = ["Theedon <faniyantoyin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
langchain = "^0.2.3"
requests = "^2.32.3"
uvicorn = "^0.30.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
